language: php
sudo: false
branches:
  only:
    - master
    - /^feature\/.*$/

matrix:
  fast_finish: true
  include:
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - schreiner.tim@gmail.com

before_install:
  - composer self-update
  - composer --version

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

script:
  - >
    echo;
    echo "Running php lint...";
    find ./src -type f -name \*.php -exec php -l {} > /dev/null \; && echo $?
  - >
    echo;
    echo "Running PHP CodeSniffer";
    composer phpcs
  - >
    echo;
    echo "Running unit tests...";
    vendor/bin/phpunit tests/